/**
 * A curated subset of MDI icons relevant to scheduling event types (food,
 * drink, music, activities, weather, etc.) -- not the full ~7000-icon MDI
 * set, which would make the picker grid unusable. IconColorPicker's search
 * box also accepts typing any other "mdi-x" name directly, so this list
 * only needs to cover the common cases, not be exhaustive.
 */
export const AGENDA_ICON_CATALOG: string[] = [
  'mdi-bullhorn-variant',
  'mdi-calendar-star',
  'mdi-star',
  'mdi-party-popper',
  'mdi-music',
  'mdi-microphone',
  'mdi-headphones',
  'mdi-disc',
  'mdi-guitar-acoustic',
  'mdi-piano',
  'mdi-beer',
  'mdi-glass-wine',
  'mdi-glass-cocktail',
  'mdi-coffee',
  'mdi-food-drumstick',
  'mdi-pizza',
  'mdi-cupcake',
  'mdi-cash-multiple',
  'mdi-dice-multiple',
  'mdi-cards-playing',
  'mdi-gamepad-variant',
  'mdi-controller-classic',
  'mdi-movie-open',
  'mdi-movie',
  'mdi-television-classic',
  'mdi-theater',
  'mdi-book-open-variant',
  'mdi-brain',
  'mdi-lightbulb-on',
  'mdi-run',
  'mdi-bike',
  'mdi-swim',
  'mdi-soccer',
  'mdi-basketball',
  'mdi-trophy',
  'mdi-medal',
  'mdi-flag-checkered',
  'mdi-tent',
  'mdi-campfire',
  'mdi-fire',
  'mdi-weather-sunny',
  'mdi-weather-night',
  'mdi-weather-partly-cloudy',
  'mdi-sleep',
  'mdi-sleep-off',
  'mdi-alarm',
  'mdi-clock-outline',
  'mdi-gift',
  'mdi-balloon',
  'mdi-cake-variant',
  'mdi-ghost',
  'mdi-robot',
  'mdi-alien',
  'mdi-rocket-launch',
  'mdi-palette',
  'mdi-camera',
  'mdi-image-multiple',
  'mdi-account-group',
  'mdi-account-voice',
  'mdi-map-marker',
  'mdi-compass',
  'mdi-bus',
  'mdi-car',
  'mdi-bicycle',
  'mdi-ferry',
  'mdi-airplane',
  'mdi-paw',
  'mdi-dog',
  'mdi-cat',
  'mdi-emoticon-happy',
  'mdi-emoticon-cool',
  'mdi-heart',
  'mdi-thumb-up',
  'mdi-shield-star',
  'mdi-crown',
];

export function filterIcons(query: string): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return AGENDA_ICON_CATALOG;
  return AGENDA_ICON_CATALOG.filter((icon) => icon.includes(q));
}
